name: Semantic Release

on:
  push:
    branches:
      - main  # or any other branch you want to release from

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # It's important to fetch all history for `semantic-release` to work

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Run semantic release
        run: bun run semantic-release

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # If you're publishing to npm, you need to set this in your repo secrets
        run: npx semantic-release
